
setup_tasks:
 - mvn -B -q versions:display-dependency-updates
 - mvn -B -q clean install -DskipTests=true

tasks:
 - mvn -B -q checkstyle:check
 - mvn -B pmd:check -Dpmd.printFailingErrors=true
 - mvn -B findbugs:check
 - mvn -B test

